(function () {
  "use strict";
  const Mitre = (window.Mitre = window.Mitre || {});

  Mitre.dom = {
    tacticsContainer: document.getElementById("tactics-container"),
    topScrollbar: document.getElementById("tactics-scrollbar"),
    topScrollbarInner: document.getElementById("tactics-scrollbar-inner"),
    tacticTemplate: document.getElementById("tactic-template"),
    techniqueTemplate: document.getElementById("technique-template"),
    subtechTemplate: document.getElementById("subtech-template"),

    generateBtn: document.getElementById("generate-btn"),
    generateFstecBtn: document.getElementById("generate-fstec-btn"),
    selectAllBtn: document.getElementById("select-all-btn"),
    clearBtn: document.getElementById("clear-btn"),
    selectionCounter: document.getElementById("selection-counter"),
    presetSelect: document.getElementById("preset-select"),
    presetNameInput: document.getElementById("preset-name"),
    savePresetBtn: document.getElementById("save-preset-btn"),
    deletePresetBtn: document.getElementById("delete-preset-btn"),
    importInput: document.getElementById("drawio-import"),
    importBtn: document.getElementById("import-btn"),
    importStatus: document.getElementById("import-status"),
    greenFilterToggle: document.getElementById("green-filter-toggle"),
    pageFitSize: document.getElementById("page-fit-size"),
    pageFitOrientation: document.getElementById("page-fit-orientation"),
    pageFitFlow: document.getElementById("page-fit-flow"),
    pageFitWidth: document.getElementById("page-fit-width"),
    pageFitWidthRange: document.getElementById("page-fit-width-range"),
    pageFitWidthMode: document.getElementById("page-fit-width-mode"),
    pageFitFont: document.getElementById("page-fit-font"),
    pageFitFontRange: document.getElementById("page-fit-font-range"),
    pvFont: document.getElementById("pv-font"),
    pvFontValue: document.getElementById("pv-font-value"),
    pvSize: document.getElementById("pv-size"),
    pvOrientation: document.getElementById("pv-orientation"),
    pvFlow: document.getElementById("pv-flow"),
    pvWidth: document.getElementById("pv-width"),
    pvWidthValue: document.getElementById("pv-width-value"),
    pvReset: document.getElementById("pv-reset"),
    pvReadout: document.getElementById("pv-readout"),
    pageFitHint: document.getElementById("page-fit-hint"),
    settingsToggleBtn: document.getElementById("settings-toggle"),
    settingsPanel: document.getElementById("settings-panel"),
    textImportTextarea: document.getElementById("text-import-textarea"),
    textImportBtn: document.getElementById("text-import-btn"),
    textImportClearToggle: document.getElementById("text-import-clear-toggle"),
    textImportStatus: document.getElementById("text-import-status"),
    previewToggleBtn: document.getElementById("preview-toggle-btn"),
    previewWindow: document.getElementById("preview-window"),
    previewCloseBtn: document.getElementById("preview-close-btn"),
    previewModeMitre: document.getElementById("preview-mode-mitre"),
    previewModeFstec: document.getElementById("preview-mode-fstec"),
    previewWorkspace: document.getElementById("preview-workspace"),
    tacticsTabbar: document.getElementById("tactics-tabbar"),
    subtechToggle: document.getElementById("subtech-toggle"),
    legendBtn: document.getElementById("legend-btn"),
    legendPopover: document.getElementById("legend-popover"),
  };
})();
